### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by JanecekPetr** [tarasp/fernflower-eclipse-plugin#1]
So, um, is there any way to use this yet except of building this on my own? And if I did build it on my own, would it work already?

**Comment by tarasp** [comment]
Hi Petr,

Unfortunately work on the plugin is not finished. Settings for fernflower
decompiler CLI options are not implemented. What is the reason you are
asking?

Regards
Taras

**Comment by JanecekPetr** [comment]
I was just looking for a solid Eclipse-capable decompiler other than the JD as it was crashing on me. Thank you for your answer.
